module.exports = Object.freeze({
  BACKORDERED: 1,
  ORDERED: 2,
  IN_STOCK: 3,
  PRE_ORDERED: 4,
  RESERVED: 5,
  PAID: 6,
  PASSED: 7,
  NEW_REQUEST: 8,
  REMOVED: 9,
  WISHLISTED_WITH_SUPPLIER: 10,
});
